apiVersion: v2
name: ia-aip-frontend
home: https://github.com/hmcts/ia-aip-frontend
version: 0.0.33
description: IA AIP Frontend
dependencies:
  - name: nodejs
    version: ~2.4.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: redis
    version: "10.0.0"
    repository: "https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami"
    tags:
      - pr
  - name: idam-pr
    version: ~2.2.6
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - idam-pr
