apiVersion: v2
name: ia-aip-frontend
home: https://github.com/hmcts/ia-aip-frontend
version: 0.0.26
description: IA AIP Frontend
dependencies:
  - name: nodejs
    version: ~2.3.7
    repository: '@hmctspublic'
  - name: redis
    version: "10.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - pr
  - name: idam-pr
    version: ~2.2.6
    repository: '@hmctspublic'
    tags:
      - idam-pr
