tags:
  - idam-pr
idam-pr:
  redirect_uris:
    IAC:
    - https://${SERVICE_FQDN}/redirectUrl
nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_WEB_URL: https://idam-web-public.aat.platform.hmcts.net
    IDAM_API_URL: http://idam-api.aat.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    CCD_API_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
