nodejs:
  image: 'https://hmctspublic.azurecr.io/ia/aip-frontend:latest'
  ingressHost: "ia-aip-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal" # override in public facing environments
  applicationPort: 3000
  memoryRequests: 256Mi
  cpuRequests: 0.2
  memoryLimits: 512Mi
  cpuLimits: 1
  environment:
    HTTP_PROTOCOL: http
    NODE_ENV: production
    S2S_MICROSERVICE_NAME: iac
    MICROSERVICE: iac
    IDAM_WEB_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_API_URL: "http://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    REDIS_URL: redis://${SERVICE_NAME}-redis-master
    SECURE_SESSION: true
    TRIGGER_BUILD: "trigger"
  aadIdentityName: ia
  keyVaults:
    ia:
      secrets:
        - idam-secret
        - addressLookupToken
        - s2s-secret
        - ia-redis-access-key
        - ia-redis-connection-string
redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
tags:
  idam-pr: false
  pr: false
