tags:
  - idam-pr
idam-pr:
  redirect_uris:
    IAC:
      - https://${SERVICE_FQDN}/redirectUrl
nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_WEB_URL: https://idam-web-public.aat.platform.hmcts.net
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    CCD_API_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
    REDIS_URL: redis://{{ .Release.Name }}-redis-master
    PCQ_URL: https://pcq.aat.platform.hmcts.net
    PCQ_RETURN_URL: https://${SERVICE_FQDN}/about-appeal
    NODE_ENV: development
    TEST: 1
  keyVaults:
    ia:
      secrets:
        - idam-secret
        - addressLookupToken
        - s2s-secret
        - AppInsightsInstrumentationKey
        - pcq-token-key
        - launch-darkly-sdk-key
